import type { Profesor } from "./types"

export const MOCK_PROFESORES: Profesor[] = [
  {
    id: "1",
    nombre: "Antonio",
    primer_apellido: "Ruiz",
    segundo_apellido: "Delgado",
    sexo: "hombre",
    dni: "12345678X",
    direccion: "Calle Mayor 123, 3º A",
    codigo_postal: "28001",
    poblacion: "Madrid",
    municipio: "Madrid",
    provincia: "Madrid",
    telefono_fijo: "91 123 4567",
    telefono_movil: "611 222 333",
    email: "antonio.ruiz@autoescuela.com",
    vehiculo_asignado: "vehiculo_1",
    fecha_permiso_a: "2015-03-15",
    permitir_solapamiento: true,
    observaciones: "Instructor experimentado, especializado en conducción urbana.",
    permisos_habilitados: ["B", "C", "D"],
    activo: true,
    sedes: ["1", "2"], // Central y Chamberí
    tipo_clase: "ambos",
    horario: [
      { id: "1-1", dia: "lunes", hora_inicio: "09:00", hora_fin: "14:00", sede_id: "1" },
      { id: "1-2", dia: "martes", hora_inicio: "09:00", hora_fin: "14:00", sede_id: "1" },
      { id: "1-3", dia: "miercoles", hora_inicio: "16:00", hora_fin: "20:00", sede_id: "2" },
    ],
    // Legacy fields for backward compatibility
    apellidos: "Ruiz Delgado",
    telefono: "611 222 333",
  },
  {
    id: "2",
    nombre: "Carmen",
    primer_apellido: "Fernández",
    segundo_apellido: "Molina",
    sexo: "mujer",
    dni: "87654321Y",
    direccion: "Avenida de la Paz 45, 2º B",
    codigo_postal: "28016",
    poblacion: "Madrid",
    municipio: "Madrid",
    provincia: "Madrid",
    telefono_fijo: "",
    telefono_movil: "622 333 444",
    email: "carmen.fernandez@autoescuela.com",
    vehiculo_asignado: "vehiculo_2",
    fecha_permiso_a: "2018-07-20",
    permitir_solapamiento: false,
    observaciones: "Especialista en motocicletas, muy paciente con alumnos nerviosos.",
    permisos_habilitados: ["AM", "A1", "A2", "A", "B"],
    activo: true,
    sedes: ["2", "3"], // Chamberí y Getafe
    tipo_clase: "practico",
    horario: [
      { id: "2-1", dia: "lunes", hora_inicio: "10:00", hora_fin: "15:00", sede_id: "2" },
      { id: "2-2", dia: "miercoles", hora_inicio: "10:00", hora_fin: "15:00", sede_id: "2" },
      { id: "2-3", dia: "viernes", hora_inicio: "10:00", hora_fin: "15:00", sede_id: "3" },
    ],
    apellidos: "Fernández Molina",
    telefono: "622 333 444",
  },
  {
    id: "3",
    nombre: "Francisco",
    primer_apellido: "Gómez",
    segundo_apellido: "Serrano",
    sexo: "hombre",
    dni: "11223344Z",
    direccion: "Calle Alcalá 200, 1º C",
    codigo_postal: "28028",
    poblacion: "Madrid",
    municipio: "Madrid",
    provincia: "Madrid",
    telefono_fijo: "91 765 4321",
    telefono_movil: "633 444 555",
    email: "francisco.gomez@autoescuela.com",
    vehiculo_asignado: "",
    fecha_permiso_a: "2012-11-05",
    permitir_solapamiento: true,
    observaciones: "Profesor teórico con 12 años de experiencia. Muy buenas valoraciones.",
    permisos_habilitados: ["B"],
    activo: true,
    sedes: ["1"], // Solo Central
    tipo_clase: "teorico",
    horario: [
      { id: "3-1", dia: "martes", hora_inicio: "16:00", hora_fin: "20:00", sede_id: "1" },
      { id: "3-2", dia: "jueves", hora_inicio: "16:00", hora_fin: "20:00", sede_id: "1" },
      { id: "3-3", dia: "sabado", hora_inicio: "09:00", hora_fin: "13:00", sede_id: "1" },
    ],
    apellidos: "Gómez Serrano",
    telefono: "633 444 555",
  },
  {
    id: "4",
    nombre: "Isabel",
    primer_apellido: "Morales",
    segundo_apellido: "Ortega",
    sexo: "mujer",
    dni: "55667788A",
    direccion: "Calle Getafe 88, 4º D",
    codigo_postal: "28905",
    poblacion: "Getafe",
    municipio: "Getafe",
    provincia: "Madrid",
    telefono_fijo: "",
    telefono_movil: "644 555 666",
    email: "isabel.morales@autoescuela.com",
    vehiculo_asignado: "",
    fecha_permiso_a: "2016-09-12",
    permitir_solapamiento: true,
    observaciones: "Profesora en baja temporal por motivos personales.",
    permisos_habilitados: ["B", "C"],
    activo: false,
    sedes: ["3"], // Era de Getafe antes de estar inactiva
    tipo_clase: "ambos",
    horario: [], // Empty as she's inactive
    apellidos: "Morales Ortega",
    telefono: "644 555 666",
  },
  {
    id: "5",
    nombre: "Miguel",
    primer_apellido: "Santos",
    segundo_apellido: "Rivas",
    sexo: "hombre",
    dni: "99887766B",
    direccion: "Plaza España 12, 5º A",
    codigo_postal: "28013",
    poblacion: "Madrid",
    municipio: "Madrid",
    provincia: "Madrid",
    telefono_fijo: "91 888 9999",
    telefono_movil: "655 666 777",
    email: "miguel.santos@autoescuela.com",
    vehiculo_asignado: "vehiculo_3",
    fecha_permiso_a: "2020-01-08",
    permitir_solapamiento: false,
    observaciones: "Instructor joven y dinámico. Especializado en prácticas de autoescuela.",
    permisos_habilitados: ["AM", "A1", "A2", "B"],
    activo: true,
    sedes: ["1", "2", "3"], // Todas las sedes
    tipo_clase: "practico",
    horario: [
      { id: "5-1", dia: "lunes", hora_inicio: "15:00", hora_fin: "19:00", sede_id: "1" },
      { id: "5-2", dia: "martes", hora_inicio: "15:00", hora_fin: "19:00", sede_id: "2" },
      { id: "5-3", dia: "jueves", hora_inicio: "09:00", hora_fin: "13:00", sede_id: "3" },
      { id: "5-4", dia: "viernes", hora_inicio: "09:00", hora_fin: "13:00", sede_id: "1" },
    ],
    apellidos: "Santos Rivas",
    telefono: "655 666 777",
  },
]
