import type { Examen } from "./types"

export const MOCK_EXAMENES: Examen[] = [
  {
    id: "1",
    alumno_id: "1",
    alumno_nombre: "María García López",
    tipo: "teorico",
    fecha: "2026-02-15",
    hora: "09:30",
    convocatoria: "Febrero 2026 - Teórico",
    intento: 1,
    resultado: "aprobado",
    centro_examen: "DGT Madrid - Arturo Soria",
    notas: "Aprobó con buena nota.",
  },
  {
    id: "2",
    alumno_id: "1",
    alumno_nombre: "María García López",
    tipo: "practico",
    fecha: "2026-03-20",
    hora: "11:00",
    convocatoria: "Marzo 2026 - Práctico",
    intento: 1,
    resultado: "pendiente",
    centro_examen: "DGT Madrid - Arturo Soria",
    notas: null,
  },
  {
    id: "3",
    alumno_id: "2",
    alumno_nombre: "Juan Pérez Martínez",
    tipo: "teorico",
    fecha: "2025-11-10",
    hora: "10:00",
    convocatoria: "Noviembre 2025 - Teórico",
    intento: 1,
    resultado: "aprobado",
    centro_examen: "DGT Sevilla",
    notas: "Primera convocatoria, aprobó a la primera.",
  },
  {
    id: "4",
    alumno_id: "2",
    alumno_nombre: "Juan Pérez Martínez",
    tipo: "practico",
    fecha: "2026-03-25",
    hora: "09:00",
    convocatoria: "Marzo 2026 - Práctico",
    intento: 1,
    resultado: "pendiente",
    centro_examen: "DGT Sevilla",
    notas: null,
  },
  {
    id: "5",
    alumno_id: "4",
    alumno_nombre: "Carlos Fernández Ruiz",
    tipo: "teorico",
    fecha: "2025-04-20",
    hora: "09:30",
    convocatoria: "Abril 2025 - Teórico",
    intento: 1,
    resultado: "suspendido",
    centro_examen: "DGT Madrid - Arturo Soria",
    notas: "Falló en señales de tráfico.",
  },
  {
    id: "6",
    alumno_id: "4",
    alumno_nombre: "Carlos Fernández Ruiz",
    tipo: "teorico",
    fecha: "2025-06-15",
    hora: "10:00",
    convocatoria: "Junio 2025 - Teórico",
    intento: 2,
    resultado: "aprobado",
    centro_examen: "DGT Madrid - Arturo Soria",
    notas: "Segundo intento, aprobado.",
  },
  {
    id: "7",
    alumno_id: "4",
    alumno_nombre: "Carlos Fernández Ruiz",
    tipo: "practico",
    fecha: "2025-09-10",
    hora: "12:00",
    convocatoria: "Septiembre 2025 - Práctico",
    intento: 1,
    resultado: "aprobado",
    centro_examen: "DGT Madrid - Arturo Soria",
    notas: "Excelente conducción.",
  },
  {
    id: "8",
    alumno_id: "5",
    alumno_nombre: "Laura Martín González",
    tipo: "teorico",
    fecha: "2025-07-20",
    hora: "09:30",
    convocatoria: "Julio 2025 - Teórico",
    intento: 1,
    resultado: "aprobado",
    centro_examen: "DGT Madrid - Arturo Soria",
    notas: null,
  },
  {
    id: "9",
    alumno_id: "5",
    alumno_nombre: "Laura Martín González",
    tipo: "practico",
    fecha: "2025-12-05",
    hora: "10:30",
    convocatoria: "Diciembre 2025 - Práctico",
    intento: 1,
    resultado: "suspendido",
    centro_examen: "DGT Madrid - Arturo Soria",
    notas: "Error en maniobra de aparcamiento.",
  },
  {
    id: "10",
    alumno_id: "5",
    alumno_nombre: "Laura Martín González",
    tipo: "practico",
    fecha: "2026-02-20",
    hora: "11:30",
    convocatoria: "Febrero 2026 - Práctico",
    intento: 2,
    resultado: "aprobado",
    centro_examen: "DGT Madrid - Arturo Soria",
    notas: "Aprobó en el segundo intento.",
  },
  {
    id: "11",
    alumno_id: "7",
    alumno_nombre: "Sofía Díaz Moreno",
    tipo: "teorico",
    fecha: "2026-01-25",
    hora: "09:00",
    convocatoria: "Enero 2026 - Teórico",
    intento: 1,
    resultado: "aprobado",
    centro_examen: "DGT Barcelona",
    notas: null,
  },
  {
    id: "12",
    alumno_id: "8",
    alumno_nombre: "Diego Navarro Torres",
    tipo: "teorico",
    fecha: "2026-02-10",
    hora: "10:00",
    convocatoria: "Febrero 2026 - Teórico",
    intento: 1,
    resultado: "suspendido",
    centro_examen: "DGT Sevilla",
    notas: "Necesita repasar normativa de carga.",
  },
  {
    id: "13",
    alumno_id: "8",
    alumno_nombre: "Diego Navarro Torres",
    tipo: "teorico",
    fecha: "2026-03-15",
    hora: "09:30",
    convocatoria: "Marzo 2026 - Teórico",
    intento: 2,
    resultado: "pendiente",
    centro_examen: "DGT Sevilla",
    notas: null,
  },
  {
    id: "14",
    alumno_id: "10",
    alumno_nombre: "Alejandro Romero Castro",
    tipo: "teorico",
    fecha: "2025-12-18",
    hora: "09:00",
    convocatoria: "Diciembre 2025 - Teórico",
    intento: 1,
    resultado: "aprobado",
    centro_examen: "DGT Sevilla",
    notas: "Permiso D, aprobó teórico específico.",
  },
  {
    id: "15",
    alumno_id: "3",
    alumno_nombre: "Ana Rodríguez Sánchez",
    tipo: "teorico",
    fecha: "2026-04-05",
    hora: "10:00",
    convocatoria: "Abril 2026 - Teórico",
    intento: 1,
    resultado: "pendiente",
    centro_examen: "DGT Madrid - Arturo Soria",
    notas: null,
  },
]
