import type { Examen } from "./types"

// Helper: map alumno_id to sede_id
function getSedeForAlumno(alumnoId: string): string {
  const sedeMapping: Record<string, string> = {
    "1": "1", // María -> Sede Central
    "2": "1", // Juan -> Sede Central
    "5": "1", // Laura -> Sede Central
    "8": "1", // Diego -> Sede Central
    "3": "2", // Ana -> Sede Chamberí
    "4": "2", // Carlos -> Sede Chamberí
    "7": "2", // Sofía -> Sede Chamberí
    "6": "3", // Pedro -> Sede Getafe
    "9": "3", // Elena -> Sede Getafe
    "10": "3", // Alejandro -> Sede Getafe
  }
  return sedeMapping[alumnoId] || "1"
}

export const MOCK_EXAMENES: Examen[] = [
  {
    id: "1",
    alumno_id: "1",
    alumno_nombre: "María García López",
    tipo: "teorico",
    fecha: "2026-02-15",
    hora: "09:30",
    convocatoria: "Febrero 2026 - Teórico",
    intento: 1,
    resultado: "aprobado",
    centro_examen: "DGT Madrid - Arturo Soria",
    notas: "Aprobó con buena nota.",
    sede_id: getSedeForAlumno("1"),
  },
  {
    id: "2",
    alumno_id: "1",
    alumno_nombre: "María García López",
    tipo: "practico",
    fecha: "2026-03-20",
    hora: "11:00",
    convocatoria: "Marzo 2026 - Práctico",
    intento: 1,
    resultado: "pendiente",
    centro_examen: "DGT Madrid - Arturo Soria",
    notas: null,
    sede_id: getSedeForAlumno("1"),
  },
  {
    id: "3",
    alumno_id: "2",
    alumno_nombre: "Juan Pérez Martínez",
    tipo: "teorico",
    fecha: "2025-11-10",
    hora: "10:00",
    convocatoria: "Noviembre 2025 - Teórico",
    intento: 1,
    resultado: "aprobado",
    centro_examen: "DGT Madrid - Arturo Soria",
    notas: "Primera convocatoria, aprobó a la primera.",
    sede_id: getSedeForAlumno("2"),
  },
  {
    id: "4",
    alumno_id: "2",
    alumno_nombre: "Juan Pérez Martínez",
    tipo: "practico",
    fecha: "2026-03-25",
    hora: "09:00",
    convocatoria: "Marzo 2026 - Práctico",
    intento: 1,
    resultado: "pendiente",
    centro_examen: "DGT Madrid - Arturo Soria",
    notas: null,
    sede_id: getSedeForAlumno("2"),
  },
  {
    id: "5",
    alumno_id: "4",
    alumno_nombre: "Carlos Fernández Ruiz",
    tipo: "teorico",
    fecha: "2025-04-20",
    hora: "09:30",
    convocatoria: "Abril 2025 - Teórico",
    intento: 1,
    resultado: "suspendido",
    centro_examen: "DGT Madrid - Chamberí",
    notas: "Falló en señales de tráfico.",
    sede_id: getSedeForAlumno("4"),
  },
  {
    id: "6",
    alumno_id: "4",
    alumno_nombre: "Carlos Fernández Ruiz",
    tipo: "teorico",
    fecha: "2025-06-15",
    hora: "10:00",
    convocatoria: "Junio 2025 - Teórico",
    intento: 2,
    resultado: "aprobado",
    centro_examen: "DGT Madrid - Chamberí",
    notas: "Segundo intento, aprobado.",
    sede_id: getSedeForAlumno("4"),
  },
  {
    id: "7",
    alumno_id: "4",
    alumno_nombre: "Carlos Fernández Ruiz",
    tipo: "practico",
    fecha: "2025-09-10",
    hora: "12:00",
    convocatoria: "Septiembre 2025 - Práctico",
    intento: 1,
    resultado: "aprobado",
    centro_examen: "DGT Madrid - Chamberí",
    notas: "Excelente conducción.",
    sede_id: getSedeForAlumno("4"),
  },
  {
    id: "8",
    alumno_id: "5",
    alumno_nombre: "Laura Martín González",
    tipo: "teorico",
    fecha: "2025-07-20",
    hora: "09:30",
    convocatoria: "Julio 2025 - Teórico",
    intento: 1,
    resultado: "aprobado",
    centro_examen: "DGT Madrid - Arturo Soria",
    notas: null,
    sede_id: getSedeForAlumno("5"),
  },
  {
    id: "9",
    alumno_id: "5",
    alumno_nombre: "Laura Martín González",
    tipo: "practico",
    fecha: "2025-12-05",
    hora: "10:30",
    convocatoria: "Diciembre 2025 - Práctico",
    intento: 1,
    resultado: "suspendido",
    centro_examen: "DGT Madrid - Arturo Soria",
    notas: "Error en maniobra de aparcamiento.",
    sede_id: getSedeForAlumno("5"),
  },
  {
    id: "10",
    alumno_id: "5",
    alumno_nombre: "Laura Martín González",
    tipo: "practico",
    fecha: "2026-02-20",
    hora: "11:30",
    convocatoria: "Febrero 2026 - Práctico",
    intento: 2,
    resultado: "aprobado",
    centro_examen: "DGT Madrid - Arturo Soria",
    notas: "Aprobó en el segundo intento.",
    sede_id: getSedeForAlumno("5"),
  },
  {
    id: "11",
    alumno_id: "7",
    alumno_nombre: "Sofía Díaz Moreno",
    tipo: "teorico",
    fecha: "2026-01-25",
    hora: "09:00",
    convocatoria: "Enero 2026 - Teórico",
    intento: 1,
    resultado: "aprobado",
    centro_examen: "DGT Madrid - Chamberí",
    notas: null,
    sede_id: getSedeForAlumno("7"),
  },
  {
    id: "12",
    alumno_id: "8",
    alumno_nombre: "Diego Navarro Torres",
    tipo: "teorico",
    fecha: "2026-02-10",
    hora: "10:00",
    convocatoria: "Febrero 2026 - Teórico",
    intento: 1,
    resultado: "suspendido",
    centro_examen: "DGT Madrid - Arturo Soria",
    notas: "Necesita repasar normativa de carga.",
    sede_id: getSedeForAlumno("8"),
  },
  {
    id: "13",
    alumno_id: "8",
    alumno_nombre: "Diego Navarro Torres",
    tipo: "teorico",
    fecha: "2026-03-15",
    hora: "09:30",
    convocatoria: "Marzo 2026 - Teórico",
    intento: 2,
    resultado: "pendiente",
    centro_examen: "DGT Madrid - Arturo Soria",
    notas: null,
    sede_id: getSedeForAlumno("8"),
  },
  {
    id: "14",
    alumno_id: "10",
    alumno_nombre: "Alejandro Romero Castro",
    tipo: "teorico",
    fecha: "2025-12-18",
    hora: "09:00",
    convocatoria: "Diciembre 2025 - Teórico",
    intento: 1,
    resultado: "aprobado",
    centro_examen: "DGT Getafe",
    notas: "Permiso D, aprobó teórico específico.",
    sede_id: getSedeForAlumno("10"),
  },
  {
    id: "15",
    alumno_id: "3",
    alumno_nombre: "Ana Rodríguez Sánchez",
    tipo: "teorico",
    fecha: "2026-04-05",
    hora: "10:00",
    convocatoria: "Abril 2026 - Teórico",
    intento: 1,
    resultado: "pendiente",
    centro_examen: "DGT Madrid - Chamberí",
    notas: null,
    sede_id: getSedeForAlumno("3"),
  },
]