import type { Conversacion, Mensaje } from "./types"

// Helper to generate dates relative to "now" (2026-03-20)
const now = new Date("2026-03-20T10:30:00")
function ago(minutes: number): string {
  return new Date(now.getTime() - minutes * 60000).toISOString()
}

export const MOCK_CONVERSACIONES: Conversacion[] = [
  // --- WhatsApp (5) ---
  {
    id: "conv-1",
    canal: "whatsapp",
    contacto_nombre: "María García",
    contacto_telefono: "+34 612 345 678",
    contacto_email: null,
    contacto_instagram: null,
    alumno_id: "alumno-12",
    estado: "abierta",
    prioridad: "media",
    asignado_a: "Laura Martínez",
    ultimo_mensaje: "¿A qué hora es mi próxima clase? No me acuerdo si era martes o miércoles",
    ultimo_mensaje_fecha: ago(5),
    mensajes_no_leidos: 2,
    etiquetas: ["clase", "horario"],
  },
  {
    id: "conv-2",
    canal: "whatsapp",
    contacto_nombre: "Juan Pérez",
    contacto_telefono: "+34 678 901 234",
    contacto_email: null,
    contacto_instagram: null,
    alumno_id: "alumno-7",
    estado: "abierta",
    prioridad: "alta",
    asignado_a: null,
    ultimo_mensaje: "Perfecto, mañana a las 9 estaré allí. ¡Deseadme suerte!",
    ultimo_mensaje_fecha: ago(35),
    mensajes_no_leidos: 0,
    etiquetas: ["examen"],
  },
  {
    id: "conv-3",
    canal: "whatsapp",
    contacto_nombre: "Antonio López",
    contacto_telefono: "+34 655 432 109",
    contacto_email: null,
    contacto_instagram: null,
    alumno_id: null,
    estado: "nueva",
    prioridad: "media",
    asignado_a: null,
    ultimo_mensaje: "Buenos días, quería preguntar cuánto cuesta el carnet B para mi hija que cumple 18 en abril",
    ultimo_mensaje_fecha: ago(120),
    mensajes_no_leidos: 3,
    etiquetas: ["precio", "nuevo alumno"],
  },
  {
    id: "conv-4",
    canal: "whatsapp",
    contacto_nombre: "Ana Rodríguez",
    contacto_telefono: "+34 699 876 543",
    contacto_email: null,
    contacto_instagram: null,
    alumno_id: "alumno-22",
    estado: "pendiente",
    prioridad: "media",
    asignado_a: "Laura Martínez",
    ultimo_mensaje: "Aquí os envío la foto de mi DNI por ambas caras",
    ultimo_mensaje_fecha: ago(300),
    mensajes_no_leidos: 1,
    etiquetas: ["documentación"],
  },
  {
    id: "conv-5",
    canal: "whatsapp",
    contacto_nombre: "Carlos Fernández",
    contacto_telefono: "+34 622 111 333",
    contacto_email: null,
    contacto_instagram: null,
    alumno_id: null,
    estado: "nueva",
    prioridad: "baja",
    asignado_a: null,
    ultimo_mensaje: "Hola, ¿hacéis también el carnet A2 de moto? ¿Cuánto costaría?",
    ultimo_mensaje_fecha: ago(480),
    mensajes_no_leidos: 1,
    etiquetas: ["moto", "A2", "precio"],
  },
  // --- Instagram (3) ---
  {
    id: "conv-6",
    canal: "instagram",
    contacto_nombre: "lucia_martinez99",
    contacto_telefono: null,
    contacto_email: null,
    contacto_instagram: "@lucia_martinez99",
    alumno_id: null,
    estado: "nueva",
    prioridad: "baja",
    asignado_a: null,
    ultimo_mensaje: "Hola! Cuánto cuesta sacar el carnet? Vi vuestro post y me interesa",
    ultimo_mensaje_fecha: ago(90),
    mensajes_no_leidos: 1,
    etiquetas: ["precio", "redes sociales"],
  },
  {
    id: "conv-7",
    canal: "instagram",
    contacto_nombre: "david_photo_bcn",
    contacto_telefono: null,
    contacto_email: null,
    contacto_instagram: "@david_photo_bcn",
    alumno_id: null,
    estado: "abierta",
    prioridad: "baja",
    asignado_a: null,
    ultimo_mensaje: "Acabo de compartir vuestra story! Me encanta cómo enseñáis 🚗",
    ultimo_mensaje_fecha: ago(1440),
    mensajes_no_leidos: 0,
    etiquetas: ["redes sociales"],
  },
  {
    id: "conv-8",
    canal: "instagram",
    contacto_nombre: "elena_drives",
    contacto_telefono: null,
    contacto_email: null,
    contacto_instagram: "@elena_drives",
    alumno_id: "alumno-15",
    estado: "abierta",
    prioridad: "baja",
    asignado_a: null,
    ultimo_mensaje: "APROBADAAA!!! 🎉🎉🎉 Gracias por todo, sois los mejores!!",
    ultimo_mensaje_fecha: ago(2880),
    mensajes_no_leidos: 0,
    etiquetas: ["aprobado"],
  },
  // --- Email (4) ---
  {
    id: "conv-9",
    canal: "email",
    contacto_nombre: "DGT — Notificaciones",
    contacto_telefono: null,
    contacto_email: "notificaciones@dgt.es",
    contacto_instagram: null,
    alumno_id: null,
    estado: "nueva",
    prioridad: "alta",
    asignado_a: null,
    ultimo_mensaje: "Resultados exámenes teóricos convocatoria 18/03/2026 — Adjunto PDF con acta de resultados",
    ultimo_mensaje_fecha: ago(60),
    mensajes_no_leidos: 1,
    etiquetas: ["DGT", "examen", "resultados"],
  },
  {
    id: "conv-10",
    canal: "email",
    contacto_nombre: "Seguros Mapfre",
    contacto_telefono: null,
    contacto_email: "renovaciones@mapfre.es",
    contacto_instagram: null,
    alumno_id: null,
    estado: "pendiente",
    prioridad: "alta",
    asignado_a: "Pedro Sánchez",
    ultimo_mensaje: "Recordatorio: la póliza del vehículo 1234-BCD vence el 01/04/2026. Adjuntamos propuesta de renovación.",
    ultimo_mensaje_fecha: ago(1500),
    mensajes_no_leidos: 0,
    etiquetas: ["seguro", "vehículo", "urgente"],
  },
  {
    id: "conv-11",
    canal: "email",
    contacto_nombre: "Editorial Ariete",
    contacto_telefono: null,
    contacto_email: "pedidos@editorialarrete.com",
    contacto_instagram: null,
    alumno_id: null,
    estado: "abierta",
    prioridad: "media",
    asignado_a: "Pedro Sánchez",
    ultimo_mensaje: "Factura N.º 2026-0487 por material didáctico — Importe: 342,50€",
    ultimo_mensaje_fecha: ago(4320),
    mensajes_no_leidos: 0,
    etiquetas: ["factura", "material"],
  },
  {
    id: "conv-12",
    canal: "email",
    contacto_nombre: "Roberto Díaz Alumno",
    contacto_telefono: null,
    contacto_email: "roberto.diaz@gmail.com",
    contacto_instagram: null,
    alumno_id: "alumno-3",
    estado: "abierta",
    prioridad: "alta",
    asignado_a: "Laura Martínez",
    ultimo_mensaje: "Quiero presentar una queja formal por los cambios de horario de última hora del pasado viernes",
    ultimo_mensaje_fecha: ago(2000),
    mensajes_no_leidos: 1,
    etiquetas: ["queja", "horario"],
  },
]

export const MOCK_MENSAJES: Record<string, Mensaje[]> = {
  // María García — WhatsApp — schedule question
  "conv-1": [
    {
      id: "msg-1-1",
      conversacion_id: "conv-1",
      contenido: "Hola buenas tardes! Soy María, alumna de la autoescuela",
      fecha: ago(30),
      es_entrante: true,
      leido: true,
      adjuntos: null,
    },
    {
      id: "msg-1-2",
      conversacion_id: "conv-1",
      contenido: "¡Hola María! ¿En qué podemos ayudarte?",
      fecha: ago(28),
      es_entrante: false,
      leido: true,
      adjuntos: null,
    },
    {
      id: "msg-1-3",
      conversacion_id: "conv-1",
      contenido: "Quería confirmar cuándo tengo mi próxima clase práctica",
      fecha: ago(25),
      es_entrante: true,
      leido: true,
      adjuntos: null,
    },
    {
      id: "msg-1-4",
      conversacion_id: "conv-1",
      contenido: "Déjame revisar tu expediente... Tienes clase el miércoles 22 de marzo a las 10:00 con el profesor David.",
      fecha: ago(20),
      es_entrante: false,
      leido: true,
      adjuntos: null,
    },
    {
      id: "msg-1-5",
      conversacion_id: "conv-1",
      contenido: "Genial, muchas gracias!",
      fecha: ago(18),
      es_entrante: true,
      leido: true,
      adjuntos: null,
    },
    {
      id: "msg-1-6",
      conversacion_id: "conv-1",
      contenido: "¿A qué hora es mi próxima clase? No me acuerdo si era martes o miércoles",
      fecha: ago(5),
      es_entrante: true,
      leido: false,
      adjuntos: null,
    },
  ],
  // Juan Pérez — WhatsApp — exam confirmation
  "conv-2": [
    {
      id: "msg-2-1",
      conversacion_id: "conv-2",
      contenido: "Hola Juan, te recordamos que mañana tienes el examen práctico a las 9:00 en la Jefatura de Tráfico.",
      fecha: ago(180),
      es_entrante: false,
      leido: true,
      adjuntos: null,
    },
    {
      id: "msg-2-2",
      conversacion_id: "conv-2",
      contenido: "Recuerda llevar el DNI original y llegar 15 minutos antes.",
      fecha: ago(179),
      es_entrante: false,
      leido: true,
      adjuntos: null,
    },
    {
      id: "msg-2-3",
      conversacion_id: "conv-2",
      contenido: "Sí, lo tengo apuntado! Estoy un poco nervioso la verdad 😅",
      fecha: ago(120),
      es_entrante: true,
      leido: true,
      adjuntos: null,
    },
    {
      id: "msg-2-4",
      conversacion_id: "conv-2",
      contenido: "¡Tranquilo! Estás muy bien preparado. Recuerda lo que practicamos: espejos, cinturón, y conduce como siempre.",
      fecha: ago(110),
      es_entrante: false,
      leido: true,
      adjuntos: null,
    },
    {
      id: "msg-2-5",
      conversacion_id: "conv-2",
      contenido: "Perfecto, mañana a las 9 estaré allí. ¡Deseadme suerte!",
      fecha: ago(35),
      es_entrante: true,
      leido: true,
      adjuntos: null,
    },
  ],
  // Antonio López — WhatsApp — price inquiry for daughter
  "conv-3": [
    {
      id: "msg-3-1",
      conversacion_id: "conv-3",
      contenido: "Buenos días",
      fecha: ago(125),
      es_entrante: true,
      leido: false,
      adjuntos: null,
    },
    {
      id: "msg-3-2",
      conversacion_id: "conv-3",
      contenido: "Soy Antonio, padre de Claudia López",
      fecha: ago(124),
      es_entrante: true,
      leido: false,
      adjuntos: null,
    },
    {
      id: "msg-3-3",
      conversacion_id: "conv-3",
      contenido: "Buenos días, quería preguntar cuánto cuesta el carnet B para mi hija que cumple 18 en abril",
      fecha: ago(120),
      es_entrante: true,
      leido: false,
      adjuntos: null,
    },
  ],
  // Ana Rodríguez — WhatsApp — DNI photo
  "conv-4": [
    {
      id: "msg-4-1",
      conversacion_id: "conv-4",
      contenido: "Hola Ana, necesitamos una copia de tu DNI por ambas caras para completar tu matrícula.",
      fecha: ago(400),
      es_entrante: false,
      leido: true,
      adjuntos: null,
    },
    {
      id: "msg-4-2",
      conversacion_id: "conv-4",
      contenido: "Vale, ahora os la mando cuando llegue a casa",
      fecha: ago(380),
      es_entrante: true,
      leido: true,
      adjuntos: null,
    },
    {
      id: "msg-4-3",
      conversacion_id: "conv-4",
      contenido: "Aquí os envío la foto de mi DNI por ambas caras",
      fecha: ago(300),
      es_entrante: true,
      leido: false,
      adjuntos: [
        { nombre: "DNI_anverso.jpg", tipo: "image/jpeg", url: "#" },
        { nombre: "DNI_reverso.jpg", tipo: "image/jpeg", url: "#" },
      ],
    },
  ],
  // Carlos Fernández — WhatsApp — motorcycle A2
  "conv-5": [
    {
      id: "msg-5-1",
      conversacion_id: "conv-5",
      contenido: "Hola, ¿hacéis también el carnet A2 de moto? ¿Cuánto costaría?",
      fecha: ago(480),
      es_entrante: true,
      leido: false,
      adjuntos: null,
    },
  ],
  // lucia_martinez99 — Instagram — price DM
  "conv-6": [
    {
      id: "msg-6-1",
      conversacion_id: "conv-6",
      contenido: "Hola! Cuánto cuesta sacar el carnet? Vi vuestro post y me interesa",
      fecha: ago(90),
      es_entrante: true,
      leido: false,
      adjuntos: null,
    },
  ],
  // david_photo_bcn — Instagram — story mention
  "conv-7": [
    {
      id: "msg-7-1",
      conversacion_id: "conv-7",
      contenido: "Ey! Gracias por la mención en stories, nos alegra que te guste 😊",
      fecha: ago(1500),
      es_entrante: false,
      leido: true,
      adjuntos: null,
    },
    {
      id: "msg-7-2",
      conversacion_id: "conv-7",
      contenido: "De nada! Es que la verdad se nota que lo hacéis con ganas",
      fecha: ago(1480),
      es_entrante: true,
      leido: true,
      adjuntos: null,
    },
    {
      id: "msg-7-3",
      conversacion_id: "conv-7",
      contenido: "Acabo de compartir vuestra story! Me encanta cómo enseñáis 🚗",
      fecha: ago(1440),
      es_entrante: true,
      leido: true,
      adjuntos: null,
    },
  ],
  // elena_drives — Instagram — aprobado selfie
  "conv-8": [
    {
      id: "msg-8-1",
      conversacion_id: "conv-8",
      contenido: "Profe, adivina qué...",
      fecha: ago(2900),
      es_entrante: true,
      leido: true,
      adjuntos: null,
    },
    {
      id: "msg-8-2",
      conversacion_id: "conv-8",
      contenido: "¿Qué? ¡Cuéntanos!",
      fecha: ago(2895),
      es_entrante: false,
      leido: true,
      adjuntos: null,
    },
    {
      id: "msg-8-3",
      conversacion_id: "conv-8",
      contenido: "APROBADAAA!!! 🎉🎉🎉 Gracias por todo, sois los mejores!!",
      fecha: ago(2880),
      es_entrante: true,
      leido: true,
      adjuntos: [
        { nombre: "selfie_aprobada.jpg", tipo: "image/jpeg", url: "#" },
      ],
    },
    {
      id: "msg-8-4",
      conversacion_id: "conv-8",
      contenido: "¡¡Enhorabuena Elena!! 🥳 Sabíamos que lo ibas a conseguir. ¡A disfrutar de la carretera!",
      fecha: ago(2870),
      es_entrante: false,
      leido: true,
      adjuntos: null,
    },
  ],
  // DGT — Email — exam results
  "conv-9": [
    {
      id: "msg-9-1",
      conversacion_id: "conv-9",
      contenido: "Estimada autoescuela,\n\nAdjuntamos el acta de resultados de la convocatoria de exámenes teóricos del 18/03/2026.\n\nAlumnos presentados: 8\nAprobados: 6\nSuspensos: 2\n\nPueden consultar el detalle en el documento adjunto.\n\nSaludos,\nDirección General de Tráfico",
      fecha: ago(60),
      es_entrante: true,
      leido: false,
      adjuntos: [
        { nombre: "Acta_Resultados_180326.pdf", tipo: "application/pdf", url: "#" },
      ],
    },
  ],
  // Seguros Mapfre — Email — policy renewal
  "conv-10": [
    {
      id: "msg-10-1",
      conversacion_id: "conv-10",
      contenido: "Estimados señores,\n\nLe informamos que la póliza de seguro del vehículo con matrícula 1234-BCD vence el próximo 01/04/2026.\n\nAdjuntamos la propuesta de renovación con las siguientes condiciones:\n- Prima anual: 1.450€\n- Cobertura: Todo riesgo\n- Franquicia: 300€\n\nQuedamos a su disposición.\nDepartamento de Renovaciones\nMapfre Seguros",
      fecha: ago(2000),
      es_entrante: true,
      leido: true,
      adjuntos: [
        { nombre: "Propuesta_Renovacion_1234BCD.pdf", tipo: "application/pdf", url: "#" },
      ],
    },
    {
      id: "msg-10-2",
      conversacion_id: "conv-10",
      contenido: "Buenos días,\n\nGracias por la propuesta. ¿Sería posible reducir la franquicia a 150€? En años anteriores teníamos esa condición.\n\nSaludos,\nAutoescuela Praxi",
      fecha: ago(1600),
      es_entrante: false,
      leido: true,
      adjuntos: null,
    },
    {
      id: "msg-10-3",
      conversacion_id: "conv-10",
      contenido: "Recordatorio: la póliza del vehículo 1234-BCD vence el 01/04/2026. Adjuntamos propuesta de renovación.",
      fecha: ago(1500),
      es_entrante: true,
      leido: true,
      adjuntos: null,
    },
  ],
  // Editorial Ariete — Email — invoice
  "conv-11": [
    {
      id: "msg-11-1",
      conversacion_id: "conv-11",
      contenido: "Estimados clientes,\n\nAdjuntamos factura correspondiente al pedido de material didáctico realizado el 10/03/2026.\n\nConcepto: 50x Manual Teórico B + 20x Test de práctica\nImporte: 342,50€ (IVA incluido)\nForma de pago: Transferencia bancaria\nVencimiento: 30 días\n\nEditorial Ariete",
      fecha: ago(4400),
      es_entrante: true,
      leido: true,
      adjuntos: [
        { nombre: "Factura_2026-0487.pdf", tipo: "application/pdf", url: "#" },
      ],
    },
    {
      id: "msg-11-2",
      conversacion_id: "conv-11",
      contenido: "Recibida, gracias. Procederemos al pago esta semana.",
      fecha: ago(4350),
      es_entrante: false,
      leido: true,
      adjuntos: null,
    },
    {
      id: "msg-11-3",
      conversacion_id: "conv-11",
      contenido: "Factura N.º 2026-0487 por material didáctico — Importe: 342,50€",
      fecha: ago(4320),
      es_entrante: true,
      leido: true,
      adjuntos: null,
    },
  ],
  // Roberto Díaz — Email — formal complaint
  "conv-12": [
    {
      id: "msg-12-1",
      conversacion_id: "conv-12",
      contenido: "Estimados,\n\nQuiero presentar una queja formal por los cambios de horario de última hora del pasado viernes 14 de marzo.\n\nTenía una clase práctica programada a las 17:00 y me avisaron solo 30 minutos antes de que se cancelaba por \"problemas logísticos\". Esto es la segunda vez que ocurre en un mes.\n\nMe parece una falta de respeto hacia los alumnos que organizamos nuestra agenda en función de estas clases. Espero una explicación y una solución.\n\nAtentamente,\nRoberto Díaz",
      fecha: ago(2100),
      es_entrante: true,
      leido: true,
      adjuntos: null,
    },
    {
      id: "msg-12-2",
      conversacion_id: "conv-12",
      contenido: "Estimado Roberto,\n\nLamentamos mucho las molestias causadas. Entendemos su frustración y tiene toda la razón. Hemos revisado lo ocurrido y se debió a una avería del vehículo de prácticas.\n\nComo compensación, le ofrecemos una clase práctica adicional sin coste. ¿Le vendría bien el lunes a las 17:00?\n\nDisculpe de nuevo las molestias.\nAutoescuela Praxi",
      fecha: ago(2050),
      es_entrante: false,
      leido: true,
      adjuntos: null,
    },
    {
      id: "msg-12-3",
      conversacion_id: "conv-12",
      contenido: "Quiero presentar una queja formal por los cambios de horario de última hora del pasado viernes",
      fecha: ago(2000),
      es_entrante: true,
      leido: false,
      adjuntos: null,
    },
  ],
}

export function getTotalUnreadCount(): number {
  return MOCK_CONVERSACIONES.reduce((sum, c) => sum + c.mensajes_no_leidos, 0)
}
