import type { TramiteDGT } from "./types"

export const MOCK_TRAMITES: TramiteDGT[] = [
  {
    id: "t1",
    alumno_id: "1",
    alumno_nombre: "María García López",
    tipo: "alta_alumno",
    estado: "completado",
    fecha_inicio: "2025-09-05",
    fecha_resolucion: "2025-09-12",
    numero_expediente: "EXP-2025-001234",
    centro_dgt: "DGT Madrid - Arturo Soria",
    documentos: ["Fotografía carnet", "DNI (original + copia)", "Certificado médico", "Justificante tasa 790-062"],
    documentos_entregados: ["Fotografía carnet", "DNI (original + copia)", "Certificado médico", "Justificante tasa 790-062"],
    notas: "Tramitación sin incidencias.",
    tasa_pagada: true,
    importe_tasa: 94.05,
  },
  {
    id: "t2",
    alumno_id: "2",
    alumno_nombre: "Juan Pérez Martínez",
    tipo: "presentacion_teorico",
    estado: "completado",
    fecha_inicio: "2025-10-01",
    fecha_resolucion: "2025-10-15",
    numero_expediente: "EXP-2025-001567",
    centro_dgt: "DGT Madrid - Arturo Soria",
    documentos: ["DNI (original)", "Justificante tasa 790-062", "Certificado aptitud centro"],
    documentos_entregados: ["DNI (original)", "Justificante tasa 790-062", "Certificado aptitud centro"],
    notas: null,
    tasa_pagada: true,
    importe_tasa: 94.05,
  },
  {
    id: "t3",
    alumno_id: "3",
    alumno_nombre: "Ana Rodríguez Sánchez",
    tipo: "alta_alumno",
    estado: "en_proceso",
    fecha_inicio: "2026-01-20",
    fecha_resolucion: null,
    numero_expediente: "EXP-2026-000123",
    centro_dgt: "DGT Sevilla - Parque Tecnológico",
    documentos: ["Fotografía carnet", "DNI (original + copia)", "Certificado médico", "Justificante tasa 790-062"],
    documentos_entregados: ["Fotografía carnet", "DNI (original + copia)"],
    notas: "Pendiente certificado médico del alumno.",
    tasa_pagada: true,
    importe_tasa: 94.05,
  },
  {
    id: "t4",
    alumno_id: "4",
    alumno_nombre: "Carlos Fernández Ruiz",
    tipo: "presentacion_practico",
    estado: "pendiente",
    fecha_inicio: "2026-03-10",
    fecha_resolucion: null,
    numero_expediente: null,
    centro_dgt: "DGT Madrid - Arturo Soria",
    documentos: ["DNI (original)", "Justificante tasa 790-062", "Certificado teórico aprobado"],
    documentos_entregados: ["DNI (original)"],
    notas: "Esperando fecha de examen práctico.",
    tasa_pagada: false,
    importe_tasa: 94.05,
  },
  {
    id: "t5",
    alumno_id: "5",
    alumno_nombre: "Laura Martín Torres",
    tipo: "expedicion_carnet",
    estado: "en_proceso",
    fecha_inicio: "2026-02-28",
    fecha_resolucion: null,
    numero_expediente: "EXP-2026-000456",
    centro_dgt: "DGT Sevilla - Parque Tecnológico",
    documentos: ["DNI (original + copia)", "Fotografía carnet", "Certificado médico", "Justificante tasa 790-062", "Certificado práctico aprobado"],
    documentos_entregados: ["DNI (original + copia)", "Fotografía carnet", "Certificado médico", "Justificante tasa 790-062", "Certificado práctico aprobado"],
    notas: "Toda la documentación entregada. Pendiente de recibir carnet.",
    tasa_pagada: true,
    importe_tasa: 94.05,
  },
  {
    id: "t6",
    alumno_id: "6",
    alumno_nombre: "Pedro López Hernández",
    tipo: "renovacion",
    estado: "rechazado",
    fecha_inicio: "2026-01-05",
    fecha_resolucion: "2026-01-20",
    numero_expediente: "EXP-2026-000089",
    centro_dgt: "DGT Madrid - Arturo Soria",
    documentos: ["DNI (original + copia)", "Fotografía carnet", "Certificado médico", "Carnet anterior", "Justificante tasa 790-062"],
    documentos_entregados: ["DNI (original + copia)", "Fotografía carnet", "Carnet anterior", "Justificante tasa 790-062"],
    notas: "Rechazado: certificado médico caducado. Debe renovar el certificado médico.",
    tasa_pagada: true,
    importe_tasa: 94.05,
  },
  {
    id: "t7",
    alumno_id: "7",
    alumno_nombre: "Sofía Díaz Moreno",
    tipo: "alta_alumno",
    estado: "pendiente",
    fecha_inicio: "2026-03-15",
    fecha_resolucion: null,
    numero_expediente: null,
    centro_dgt: "DGT Madrid - Arturo Soria",
    documentos: ["Fotografía carnet", "DNI (original + copia)", "Certificado médico", "Justificante tasa 790-062"],
    documentos_entregados: [],
    notas: "Recién matriculada. Pendiente recopilar documentación.",
    tasa_pagada: false,
    importe_tasa: 94.05,
  },
  {
    id: "t8",
    alumno_id: "8",
    alumno_nombre: "Diego Romero Navarro",
    tipo: "presentacion_teorico",
    estado: "pendiente",
    fecha_inicio: "2026-03-18",
    fecha_resolucion: null,
    numero_expediente: null,
    centro_dgt: "DGT Sevilla - Parque Tecnológico",
    documentos: ["DNI (original)", "Justificante tasa 790-062", "Certificado aptitud centro"],
    documentos_entregados: ["DNI (original)", "Certificado aptitud centro"],
    notas: "Falta justificante de tasa.",
    tasa_pagada: false,
    importe_tasa: 94.05,
  },
  {
    id: "t9",
    alumno_id: "9",
    alumno_nombre: "Elena Jiménez Vega",
    tipo: "duplicado",
    estado: "completado",
    fecha_inicio: "2026-02-01",
    fecha_resolucion: "2026-02-20",
    numero_expediente: "EXP-2026-000234",
    centro_dgt: "DGT Madrid - Arturo Soria",
    documentos: ["DNI (original + copia)", "Fotografía carnet", "Denuncia por extravío/robo", "Justificante tasa 790-062"],
    documentos_entregados: ["DNI (original + copia)", "Fotografía carnet", "Denuncia por extravío/robo", "Justificante tasa 790-062"],
    notas: "Duplicado por extravío. Carnet recibido.",
    tasa_pagada: true,
    importe_tasa: 20.81,
  },
  {
    id: "t10",
    alumno_id: "10",
    alumno_nombre: "Álvaro Castro Gil",
    tipo: "presentacion_practico",
    estado: "en_proceso",
    fecha_inicio: "2026-03-05",
    fecha_resolucion: null,
    numero_expediente: "EXP-2026-000567",
    centro_dgt: "DGT Sevilla - Parque Tecnológico",
    documentos: ["DNI (original)", "Justificante tasa 790-062", "Certificado teórico aprobado"],
    documentos_entregados: ["DNI (original)", "Justificante tasa 790-062", "Certificado teórico aprobado"],
    notas: "Examen práctico programado para el 25/03/2026.",
    tasa_pagada: true,
    importe_tasa: 94.05,
  },
]
