import type { Factura, PagoFactura } from "./types"

// Helper: map alumno_id to sede_id
function getSedeForAlumno(alumnoId: string): string {
  const sedeMapping: Record<string, string> = {
    "1": "1", // María -> Sede Central
    "2": "1", // Juan -> Sede Central
    "5": "1", // Laura -> Sede Central
    "8": "1", // Diego -> Sede Central
    "3": "2", // Ana -> Sede Chamberí
    "4": "2", // Carlos -> Sede Chamberí
    "7": "2", // Sofía -> Sede Chamberí
    "6": "3", // Pedro -> Sede Getafe
    "9": "3", // Elena -> Sede Getafe
    "10": "3", // Alejandro -> Sede Getafe
  }
  return sedeMapping[alumnoId] || "1"
}

export const MOCK_FACTURAS: Factura[] = [
  {
    id: "1",
    numero: "FAC-2026-001",
    alumno_id: "1",
    alumno_nombre: "María García López",
    fecha_emision: "2025-09-10",
    fecha_vencimiento: "2025-10-10",
    lineas: [
      {
        id: "l1",
        concepto: "matricula",
        descripcion: "Matrícula permiso B",
        cantidad: 1,
        precio_unitario: 250,
        subtotal: 250,
      },
      {
        id: "l2",
        concepto: "bono_clases",
        descripcion: "Bono 10 clases prácticas",
        cantidad: 1,
        precio_unitario: 450,
        subtotal: 450,
      },
    ],
    total: 700,
    estado: "pagada",
    metodo_pago: "tarjeta",
    fecha_pago: "2025-09-12",
    notas: null,
    sede_id: "1",
  },
  {
    id: "2",
    numero: "FAC-2026-002",
    alumno_id: "2",
    alumno_nombre: "Juan Pérez Martínez",
    fecha_emision: "2025-06-20",
    fecha_vencimiento: "2025-07-20",
    lineas: [
      {
        id: "l3",
        concepto: "matricula",
        descripcion: "Matrícula permiso B",
        cantidad: 1,
        precio_unitario: 280,
        subtotal: 280,
      },
    ],
    total: 280,
    estado: "pagada",
    metodo_pago: "transferencia",
    fecha_pago: "2025-06-22",
    notas: null,
    sede_id: "1",
  },
  {
    id: "3",
    numero: "FAC-2026-003",
    alumno_id: "2",
    alumno_nombre: "Juan Pérez Martínez",
    fecha_emision: "2026-01-15",
    fecha_vencimiento: "2026-02-15",
    lineas: [
      {
        id: "l4",
        concepto: "bono_clases",
        descripcion: "Bono 10 clases prácticas",
        cantidad: 1,
        precio_unitario: 450,
        subtotal: 450,
      },
      {
        id: "l5",
        concepto: "examen",
        descripcion: "Tasa examen práctico DGT",
        cantidad: 1,
        precio_unitario: 91.50,
        subtotal: 91.50,
      },
    ],
    total: 541.50,
    estado: "pendiente",
    metodo_pago: null,
    fecha_pago: null,
    notas: "Pendiente de pago antes del examen.",
    sede_id: "1",
  },
  {
    id: "4",
    numero: "FAC-2026-004",
    alumno_id: "3",
    alumno_nombre: "Ana Rodríguez Sánchez",
    fecha_emision: "2026-01-15",
    fecha_vencimiento: "2026-02-15",
    lineas: [
      {
        id: "l6",
        concepto: "matricula",
        descripcion: "Matrícula permiso AM",
        cantidad: 1,
        precio_unitario: 200,
        subtotal: 200,
      },
    ],
    total: 200,
    estado: "pagada",
    metodo_pago: "efectivo",
    fecha_pago: "2026-01-15",
    notas: "Pagado en efectivo al matricularse.",
    sede_id: "2",
  },
  {
    id: "5",
    numero: "FAC-2026-005",
    alumno_id: "4",
    alumno_nombre: "Carlos Fernández Ruiz",
    fecha_emision: "2025-02-01",
    fecha_vencimiento: "2025-03-01",
    lineas: [
      {
        id: "l7",
        concepto: "matricula",
        descripcion: "Matrícula permiso A2",
        cantidad: 1,
        precio_unitario: 300,
        subtotal: 300,
      },
      {
        id: "l8",
        concepto: "bono_clases",
        descripcion: "Bono 10 clases prácticas moto",
        cantidad: 1,
        precio_unitario: 480,
        subtotal: 480,
      },
      {
        id: "l9",
        concepto: "examen",
        descripcion: "Tasa examen teórico DGT",
        cantidad: 1,
        precio_unitario: 91.50,
        subtotal: 91.50,
      },
    ],
    total: 871.50,
    estado: "pagada",
    metodo_pago: "domiciliacion",
    fecha_pago: "2025-02-05",
    notas: null,
    sede_id: "2",
  },
  {
    id: "6",
    numero: "FAC-2026-006",
    alumno_id: "5",
    alumno_nombre: "Laura Martín González",
    fecha_emision: "2025-04-12",
    fecha_vencimiento: "2025-05-12",
    lineas: [
      {
        id: "l10",
        concepto: "matricula",
        descripcion: "Matrícula permiso B",
        cantidad: 1,
        precio_unitario: 250,
        subtotal: 250,
      },
      {
        id: "l11",
        concepto: "bono_clases",
        descripcion: "Bono 10 clases prácticas",
        cantidad: 1,
        precio_unitario: 450,
        subtotal: 450,
      },
    ],
    total: 700,
    estado: "parcial",
    metodo_pago: "tarjeta",
    fecha_pago: null,
    notas: "Pagado 400€ de 700€. Pendiente resto.",
    sede_id: "1",
  },
  {
    id: "7",
    numero: "FAC-2026-007",
    alumno_id: "7",
    alumno_nombre: "Sofía Díaz Moreno",
    fecha_emision: "2025-11-20",
    fecha_vencimiento: "2025-12-20",
    lineas: [
      {
        id: "l12",
        concepto: "matricula",
        descripcion: "Matrícula permiso A",
        cantidad: 1,
        precio_unitario: 300,
        subtotal: 300,
      },
      {
        id: "l13",
        concepto: "bono_clases",
        descripcion: "Bono 10 clases prácticas moto",
        cantidad: 1,
        precio_unitario: 480,
        subtotal: 480,
      },
    ],
    total: 780,
    estado: "pendiente",
    metodo_pago: null,
    fecha_pago: null,
    notas: null,
    sede_id: "2",
  },
  {
    id: "8",
    numero: "FAC-2026-008",
    alumno_id: "8",
    alumno_nombre: "Diego Navarro Torres",
    fecha_emision: "2025-10-01",
    fecha_vencimiento: "2025-11-01",
    lineas: [
      {
        id: "l14",
        concepto: "matricula",
        descripcion: "Matrícula permiso C",
        cantidad: 1,
        precio_unitario: 300,
        subtotal: 300,
      },
    ],
    total: 300,
    estado: "vencida",
    metodo_pago: null,
    fecha_pago: null,
    notas: "Vencida. Contactar alumno para gestionar pago.",
    sede_id: "1",
  },
  {
    id: "9",
    numero: "FAC-2026-009",
    alumno_id: "9",
    alumno_nombre: "Elena Jiménez Vega",
    fecha_emision: "2026-02-10",
    fecha_vencimiento: "2026-03-10",
    lineas: [
      {
        id: "l15",
        concepto: "matricula",
        descripcion: "Matrícula permiso AM",
        cantidad: 1,
        precio_unitario: 200,
        subtotal: 200,
      },
    ],
    total: 200,
    estado: "pendiente",
    metodo_pago: null,
    fecha_pago: null,
    notas: null,
    sede_id: "3",
  },
  {
    id: "10",
    numero: "FAC-2026-010",
    alumno_id: "10",
    alumno_nombre: "Alejandro Romero Castro",
    fecha_emision: "2025-08-15",
    fecha_vencimiento: "2025-09-15",
    lineas: [
      {
        id: "l16",
        concepto: "matricula",
        descripcion: "Matrícula permiso D",
        cantidad: 1,
        precio_unitario: 300,
        subtotal: 300,
      },
      {
        id: "l17",
        concepto: "bono_clases",
        descripcion: "Bono 10 clases prácticas autobús",
        cantidad: 1,
        precio_unitario: 550,
        subtotal: 550,
      },
    ],
    total: 850,
    estado: "parcial",
    metodo_pago: "transferencia",
    fecha_pago: null,
    notas: "Pagado 500€. Pendiente 350€.",
    sede_id: "3",
  },
  {
    id: "11",
    numero: "FAC-2026-011",
    alumno_id: "6",
    alumno_nombre: "Pedro López Hernández",
    fecha_emision: "2025-03-05",
    fecha_vencimiento: "2025-04-05",
    lineas: [
      {
        id: "l18",
        concepto: "matricula",
        descripcion: "Matrícula permiso B",
        cantidad: 1,
        precio_unitario: 250,
        subtotal: 250,
      },
    ],
    total: 250,
    estado: "anulada",
    metodo_pago: null,
    fecha_pago: null,
    notas: "Anulada por baja voluntaria del alumno.",
    sede_id: "3",
  },
  {
    id: "12",
    numero: "FAC-2026-012",
    alumno_id: "1",
    alumno_nombre: "María García López",
    fecha_emision: "2026-03-01",
    fecha_vencimiento: "2026-04-01",
    lineas: [
      {
        id: "l19",
        concepto: "clase_suelta",
        descripcion: "Clases prácticas adicionales",
        cantidad: 3,
        precio_unitario: 35,
        subtotal: 105,
      },
      {
        id: "l20",
        concepto: "examen",
        descripcion: "Tasa examen práctico DGT",
        cantidad: 1,
        precio_unitario: 91.50,
        subtotal: 91.50,
      },
    ],
    total: 196.50,
    estado: "pendiente",
    metodo_pago: null,
    fecha_pago: null,
    notas: null,
    sede_id: "1",
  },
]

export const MOCK_PAGOS: PagoFactura[] = [
  // Factura 1 (pagada - 700€)
  { id: "p1", factura_id: "1", importe: 700, fecha: "2025-09-12", metodo_pago: "tarjeta", notas: null },
  // Factura 2 (pagada - 280€)
  { id: "p2", factura_id: "2", importe: 280, fecha: "2025-06-22", metodo_pago: "transferencia", notas: null },
  // Factura 4 (pagada - 200€)
  { id: "p3", factura_id: "4", importe: 200, fecha: "2026-01-15", metodo_pago: "efectivo", notas: "Pagado en efectivo al matricularse." },
  // Factura 5 (pagada - 871.50€)
  { id: "p4", factura_id: "5", importe: 500, fecha: "2025-02-05", metodo_pago: "domiciliacion", notas: "Primer pago" },
  { id: "p5", factura_id: "5", importe: 371.50, fecha: "2025-02-15", metodo_pago: "domiciliacion", notas: "Segundo pago" },
  // Factura 6 (parcial - 400€ de 700€)
  { id: "p6", factura_id: "6", importe: 250, fecha: "2025-04-15", metodo_pago: "tarjeta", notas: "Primer pago parcial" },
  { id: "p7", factura_id: "6", importe: 150, fecha: "2025-05-01", metodo_pago: "tarjeta", notas: "Segundo pago parcial" },
  // Factura 10 (parcial - 500€ de 850€)
  { id: "p8", factura_id: "10", importe: 500, fecha: "2025-09-01", metodo_pago: "transferencia", notas: "Pago inicial" },
]
