import type { Contrato } from "./types"
import { generarContratoHTML } from "./contrato-template"

const AUTOESCUELA = {
  autoescuela_nombre: "Autoescuela Praxi",
  autoescuela_cif: "B12345678",
  autoescuela_direccion: "Calle Mayor 15, 28001 Madrid",
}

function generarContenido(alumno: string, dni: string, permiso: string, matricula: number, clases: number, fecha: string) {
  return generarContratoHTML({
    ...AUTOESCUELA,
    alumno_nombre: alumno,
    alumno_dni: dni,
    permiso,
    importe_matricula: matricula,
    importe_clases: clases,
    total: matricula + clases,
    fecha,
  })
}

export const MOCK_CONTRATOS: Contrato[] = [
  {
    id: "c1",
    alumno_id: "1",
    alumno_nombre: "María García López",
    tipo_permiso: "B",
    fecha_creacion: "2025-09-10",
    fecha_firma: "2025-09-10",
    estado: "firmado",
    contenido: generarContenido("María García López", "12345678A", "B", 200, 850, "2025-09-10"),
    firma_alumno: null,
    firma_autoescuela: true,
    importe_matricula: 200,
    importe_clases: 850,
    total: 1050,
  },
  {
    id: "c2",
    alumno_id: "2",
    alumno_nombre: "Juan Pérez Martínez",
    tipo_permiso: "B",
    fecha_creacion: "2025-06-20",
    fecha_firma: "2025-06-21",
    estado: "firmado",
    contenido: generarContenido("Juan Pérez Martínez", "23456789B", "B", 200, 850, "2025-06-20"),
    firma_alumno: null,
    firma_autoescuela: true,
    importe_matricula: 200,
    importe_clases: 850,
    total: 1050,
  },
  {
    id: "c3",
    alumno_id: "3",
    alumno_nombre: "Ana Rodríguez Sánchez",
    tipo_permiso: "AM",
    fecha_creacion: "2026-01-15",
    fecha_firma: null,
    estado: "enviado",
    contenido: generarContenido("Ana Rodríguez Sánchez", "34567890C", "AM", 100, 400, "2026-01-15"),
    firma_alumno: null,
    firma_autoescuela: true,
    importe_matricula: 100,
    importe_clases: 400,
    total: 500,
  },
  {
    id: "c4",
    alumno_id: "7",
    alumno_nombre: "Sofía Díaz Moreno",
    tipo_permiso: "A",
    fecha_creacion: "2025-11-20",
    fecha_firma: null,
    estado: "borrador",
    contenido: generarContenido("Sofía Díaz Moreno", "78901234G", "A", 250, 950, "2025-11-20"),
    firma_alumno: null,
    firma_autoescuela: false,
    importe_matricula: 250,
    importe_clases: 950,
    total: 1200,
  },
  {
    id: "c5",
    alumno_id: "6",
    alumno_nombre: "Pedro López Hernández",
    tipo_permiso: "B",
    fecha_creacion: "2025-03-05",
    fecha_firma: "2025-03-06",
    estado: "cancelado",
    contenido: generarContenido("Pedro López Hernández", "67890123F", "B", 200, 850, "2025-03-05"),
    firma_alumno: null,
    firma_autoescuela: true,
    importe_matricula: 200,
    importe_clases: 850,
    total: 1050,
  },
  {
    id: "c6",
    alumno_id: "9",
    alumno_nombre: "Elena Jiménez Vega",
    tipo_permiso: "AM",
    fecha_creacion: "2026-02-10",
    fecha_firma: null,
    estado: "enviado",
    contenido: generarContenido("Elena Jiménez Vega", "90123456J", "AM", 100, 400, "2026-02-10"),
    firma_alumno: null,
    firma_autoescuela: true,
    importe_matricula: 100,
    importe_clases: 400,
    total: 500,
  },
]
