import type { Alumno } from "./types"

export const MOCK_ALUMNOS: Alumno[] = [
  {
    id: "1",
    nombre: "María",
    apellidos: "García López",
    dni: "12345678A",
    email: "maria.garcia@email.com",
    telefono: "612 345 678",
    fecha_nacimiento: "2004-03-15",
    direccion: "Calle Gran Vía 42, 3ºB, Madrid",
    permiso: "B",
    estado: "en_curso",
    fecha_matricula: "2025-09-10",
    notas: "Alumna con buen progreso. Necesita reforzar maniobras de aparcamiento.",
  },
  {
    id: "2",
    nombre: "Juan",
    apellidos: "Pérez Martínez",
    dni: "23456789B",
    email: "juan.perez@email.com",
    telefono: "623 456 789",
    fecha_nacimiento: "2003-07-22",
    direccion: "Avenida de la Constitución 15, Sevilla",
    permiso: "B",
    estado: "teorico_aprobado",
    fecha_matricula: "2025-06-20",
    notas: "Aprobó el teórico a la primera. Pendiente inicio de prácticas.",
  },
  {
    id: "3",
    nombre: "Ana",
    apellidos: "Rodríguez Sánchez",
    dni: "34567890C",
    email: null,
    telefono: "634 567 890",
    fecha_nacimiento: "2005-01-08",
    direccion: null,
    permiso: "AM",
    estado: "matriculado",
    fecha_matricula: "2026-01-15",
    notas: null,
  },
  {
    id: "4",
    nombre: "Carlos",
    apellidos: "Fernández Ruiz",
    dni: "45678901D",
    email: "carlos.fernandez@email.com",
    telefono: "645 678 901",
    fecha_nacimiento: "1998-11-30",
    direccion: "Plaza Mayor 8, 1ºA, Valladolid",
    permiso: "A2",
    estado: "completado",
    fecha_matricula: "2025-02-01",
    notas: "Obtuvo el carnet con éxito. Excelente alumno.",
  },
  {
    id: "5",
    nombre: "Laura",
    apellidos: "Martín González",
    dni: "56789012E",
    email: "laura.martin@email.com",
    telefono: "656 789 012",
    fecha_nacimiento: "2002-05-18",
    direccion: "Calle Alcalá 120, Madrid",
    permiso: "B",
    estado: "practico_aprobado",
    fecha_matricula: "2025-04-12",
    notas: "Solo falta recoger el carnet en la DGT.",
  },
  {
    id: "6",
    nombre: "Pedro",
    apellidos: "López Hernández",
    dni: "67890123F",
    email: null,
    telefono: "667 890 123",
    fecha_nacimiento: "2004-09-25",
    direccion: "Rúa do Franco 33, Santiago de Compostela",
    permiso: "B",
    estado: "baja",
    fecha_matricula: "2025-03-05",
    notas: "Baja voluntaria. Motivo: cambio de ciudad.",
  },
  {
    id: "7",
    nombre: "Sofía",
    apellidos: "Díaz Moreno",
    dni: "78901234G",
    email: "sofia.diaz@email.com",
    telefono: "678 901 234",
    fecha_nacimiento: "2001-12-03",
    direccion: "Carrer de Balmes 50, Barcelona",
    permiso: "A",
    estado: "en_curso",
    fecha_matricula: "2025-11-20",
    notas: "Tiene experiencia previa con A2. Buen manejo de la moto.",
  },
  {
    id: "8",
    nombre: "Diego",
    apellidos: "Navarro Torres",
    dni: "89012345H",
    email: "diego.navarro@email.com",
    telefono: "689 012 345",
    fecha_nacimiento: "1995-06-14",
    direccion: "Calle Larios 22, Málaga",
    permiso: "C",
    estado: "en_curso",
    fecha_matricula: "2025-10-01",
    notas: "Necesita el C para su trabajo de transportista.",
  },
  {
    id: "9",
    nombre: "Elena",
    apellidos: "Jiménez Vega",
    dni: "90123456J",
    email: "elena.jimenez@email.com",
    telefono: "690 123 456",
    fecha_nacimiento: "2006-02-28",
    direccion: null,
    permiso: "AM",
    estado: "matriculado",
    fecha_matricula: "2026-02-10",
    notas: null,
  },
  {
    id: "10",
    nombre: "Alejandro",
    apellidos: "Romero Castro",
    dni: "01234567K",
    email: "alejandro.romero@email.com",
    telefono: "601 234 567",
    fecha_nacimiento: "2000-08-19",
    direccion: "Avenida de Andalucía 88, Granada",
    permiso: "D",
    estado: "teorico_aprobado",
    fecha_matricula: "2025-08-15",
    notas: "Conductor profesional. Busca permiso D para autobuses.",
  },
]
